//! `crypto` — ephemeral Ed25519 identity (beacon-rotating) + AEAD.
//!
//! Constant-time verify. Domain-separated signatures. Keys derived from static device seed +
//! beacon seed for forward secrecy. Persisted only via the platform `KeyStore` trait
//! (Keystore/Keychain) — never written to core-owned storage (invariant #5).
//! See README.md §2.

use chacha20poly1305::{ChaCha20Poly1305, KeyInit, Nonce, aead::Aead};
use zeroize::Zeroize;
use ed25519_dalek::{Signature, Signer, SigningKey, VerifyingKey};

pub const DOMAIN_SIG: &[u8] = b"mesh-core:v1:frame-sig";

/// A rotating ephemeral signing identity. Derived from the static device seed and the
/// per-epoch beacon seed (forward-secrecy chain). Rotates with the beacon, never persisted
/// beyond the platform secure store, wiped on panic-wipe.
pub struct Ephemeral {
    key: SigningKey,
}

/// Secure key storage owned by the platform shim (Android Keystore / iOS Keychain).
pub trait KeyStore {
    fn load_seed(&self) -> Option<[u8; 32]>;
    fn store_seed(&self, seed: &[u8; 32]);
    fn wipe(&self);
}

/// Derive an ephemeral signing key from the static device `seed` and the current `beacon_seed`.
///
/// The beacon seed provides forward secrecy: even if the static seed is extracted later,
/// past ephemeral keys cannot be recomputed without the past beacon seed — and the one-way
/// hash chain makes those unrecoverable.
pub fn from_seed(seed: &[u8; 32], beacon_seed: &[u8; 32]) -> Ephemeral {
    let mut material = [0u8; 64];
    material[..32].copy_from_slice(seed);
    material[32..].copy_from_slice(beacon_seed);
    let derived = blake3::derive_key("mesh-core:v1:ephemeral", &material);
    Ephemeral {
        key: SigningKey::from_bytes(&derived),
    }
}

/// Create a fresh ephemeral identity (random seed + random beacon seed).
/// Used for panic-wipe + restart — unlinkable to any prior identity.
pub fn rotate() -> Ephemeral {
    let mut seed = [0u8; 32];
    getrandom::fill(&mut seed).expect("OS CSPRNG unavailable");
    let mut beacon_seed = [0u8; 32];
    getrandom::fill(&mut beacon_seed).expect("OS CSPRNG unavailable");
    from_seed(&seed, &beacon_seed)
}

pub fn public_key(e: &Ephemeral) -> [u8; 32] {
    e.key.verifying_key().to_bytes()
}

pub fn sign(e: &Ephemeral, canonical: &[u8]) -> [u8; 64] {
    let msg = [DOMAIN_SIG, canonical].concat();
    e.key.sign(&msg).to_bytes()
}

pub fn verify(pk: &[u8; 32], canonical: &[u8], sig: &[u8; 64]) -> bool {
    let vk = match VerifyingKey::from_bytes(pk) {
        Ok(v) => v,
        Err(_) => return false,
    };
    let s = Signature::from_bytes(sig);
    let msg = [DOMAIN_SIG, canonical].concat();
    vk.verify_strict(&msg, &s).is_ok()
}

pub fn aead_seal(key: &[u8; 32], nonce: &[u8; 12], pt: &[u8]) -> Vec<u8> {
    ChaCha20Poly1305::new_from_slice(key)
        .expect("32-byte key")
        .encrypt(&Nonce::from(*nonce), pt)
        .expect("aead encrypt")
}

pub fn aead_open(key: &[u8; 32], nonce: &[u8; 12], ct: &[u8]) -> Option<Vec<u8>> {
    ChaCha20Poly1305::new_from_slice(key)
        .ok()?
        .decrypt(&Nonce::from(*nonce), ct)
        .ok()
}

/// X25519 public key for a long-term pairing secret. The secret is generated by the caller
/// (32 random bytes from the OS RNG) and never leaves the device.
pub fn pair_public(sk: &[u8; 32]) -> [u8; 32] {
    let secret = x25519_dalek::StaticSecret::from(*sk);
    x25519_dalek::PublicKey::from(&secret).to_bytes()
}

/// Derive the shared pairwise message key from our secret and the peer's public key.
/// Returns None if the DH output is the all-zero point (contributory behaviour check).
/// Both sides derive the identical key. Domain-separated via blake3 derive_key.
///
/// NOTE (A3): a key derived here is STATIC — a seized long-term secret recomputes it and
/// decrypts all recorded history. New pairings must use [`pair_seed_v2`] + [`pair_ratchet`].
pub fn pair_derive(our_sk: &[u8; 32], their_pk: &[u8; 32]) -> Option<[u8; 32]> {
    let secret = x25519_dalek::StaticSecret::from(*our_sk);
    let shared = secret.diffie_hellman(&x25519_dalek::PublicKey::from(*their_pk));
    if shared.as_bytes().iter().all(|&b| b == 0) {
        return None;
    }
    Some(blake3::derive_key("mesh-core:v1:pairkey", shared.as_bytes()))
}

/// v2 pairing chain seed (A3 forward secrecy).
///
/// `shared` is the [`pair_derive`] output; `salt_a`/`salt_b` are per-pairing random salts
/// exchanged out-of-band alongside the public keys at pairing time and then DELETED by both
/// sides. The salts are canonically ordered (lexicographic min first) so both parties derive
/// the same seed without knowing whose is whose.
///
/// Why this delivers actual forward secrecy: the epoch ratchet ([`pair_ratchet`]) is one-way,
/// and the chain seed cannot be recomputed from the seized long-term secret alone — the
/// deleted salts are missing entropy. A seized phone therefore yields at most the currently
/// stored chain state (present epoch forward), never past epochs.
pub fn pair_seed_v2(shared: &[u8; 32], salt_a: &[u8; 32], salt_b: &[u8; 32]) -> [u8; 32] {
    let (lo, hi) = if salt_a <= salt_b { (salt_a, salt_b) } else { (salt_b, salt_a) };
    let mut material = [0u8; 96];
    material[..32].copy_from_slice(shared);
    material[32..64].copy_from_slice(lo);
    material[64..].copy_from_slice(hi);
    let out = blake3::derive_key("mesh-core:v1:pairseed-v2", &material);
    // M5: this buffer holds the raw ECDH output. Zeroize rather than a plain assignment —
    // the compiler is free to elide writes to a dead stack buffer.
    material.zeroize();
    out
}

// ---------------------------------------------------------------------------
// Short Authentication String (SAS) for QR pairing
// ---------------------------------------------------------------------------

/// Syllable table: 16 onsets x 8 vowels x 16 codas = exactly 2048 = 2^11 words.
///
/// Generated rather than drawn from a real-word list on purpose. A 2048-entry English list
/// would be an unreviewable blob shipped into a security-critical confirmation screen, and
/// the only dictionary available here (Webster's 2nd) is dominated by words like "besnow" and
/// "abeigh" — worse to compare than syllables, with no frequency data to filter by. This
/// table is auditable at a glance, is exactly a power of two so no index is wasted or biased,
/// and is pronounceable, so the string also works read aloud.
///
/// Letters that render or sound alike are left out (c/k, q, x, y, i/j overlap in codas).
const SAS_ONSETS: [&str; 16] = [
    "b", "d", "f", "g", "h", "j", "k", "l", "m", "n", "p", "r", "s", "t", "v", "z",
];
const SAS_VOWELS: [&str; 8] = ["a", "e", "i", "o", "u", "ee", "oo", "ai"];
const SAS_CODAS: [&str; 16] = [
    "b", "d", "f", "g", "k", "l", "m", "n", "p", "r", "s", "t", "v", "z", "ch", "sh",
];

/// Number of SAS words shown to the user. 4 words x 11 bits = 44 bits.
pub const SAS_WORD_COUNT: usize = 4;

/// Short Authentication String binding a completed ECDH to the two identities involved.
///
/// QR pairing authenticates NOTHING on its own: scanning a code proves only that some code
/// was scanned, so a relay sitting between two phones can hand each of them its own key and
/// read everything afterwards. Both sides display this string and the users compare it before
/// the contact is saved. A man-in-the-middle holds two DIFFERENT shared secrets, so the two
/// screens disagree.
///
/// 44 bits, not the 20 of a 6-digit code. The attack here is not offline: the adversary
/// learns the first public key when it is displayed and can grind its own keypair to force a
/// SAS collision *while the two users are still fumbling through a sequential scan*. 2^20
/// ECDH-and-hash is under a second on one machine. 6 digits is the ZRTP number and it assumes
/// a human VOICE is authenticating liveness; two screens carry no such signal.
///
/// The public keys are sorted so both sides derive the same value without knowing whose is
/// whose. `shared` is the [`pair_derive`] output.
pub fn pair_sas(shared: &[u8; 32], pk_a: &[u8; 32], pk_b: &[u8; 32]) -> [u8; 8] {
    let (lo, hi) = if pk_a <= pk_b { (pk_a, pk_b) } else { (pk_b, pk_a) };
    let mut material = [0u8; 96];
    material[..32].copy_from_slice(shared);
    material[32..64].copy_from_slice(lo);
    material[64..].copy_from_slice(hi);
    let mut k = blake3::derive_key("mesh-core:v1:pair-sas", &material);
    let mut out = [0u8; 8];
    out.copy_from_slice(&k[..8]);
    material.zeroize();
    k.zeroize();
    out
}

/// Render a [`pair_sas`] value as [`SAS_WORD_COUNT`] words, 11 bits each.
pub fn sas_words(sas: &[u8; 8]) -> Vec<String> {
    let v = u64::from_be_bytes(*sas);
    (0..SAS_WORD_COUNT)
        .map(|i| {
            // Take the top 44 bits, 11 at a time. Each 11-bit index splits 4/3/4.
            let idx = ((v >> (64 - 11 * (i + 1))) & 0x7FF) as usize;
            format!(
                "{}{}{}",
                SAS_ONSETS[(idx >> 7) & 0xF],
                SAS_VOWELS[(idx >> 4) & 0x7],
                SAS_CODAS[idx & 0xF]
            )
        })
        .collect()
}

/// Advance a pair-chain key from `from_epoch` to `to_epoch` (A3 forward secrecy).
///
/// One step per epoch: `K_e = BLAKE3("mesh-core:v1:pairratchet" || K_{e-1} || e_be_u32)`.
/// One-way: past keys are unrecoverable from the result. Peers keep only the current and
/// one previous epoch key (clock-skew tolerance); everything older is deleted.
///
/// Returns `None` if `to_epoch < from_epoch` or the span exceeds 8192 steps (DoS bound on
/// adversarial epoch values from the wire). `to_epoch == from_epoch` returns `key` unchanged.
pub fn pair_ratchet(key: &[u8; 32], from_epoch: u32, to_epoch: u32) -> Option<[u8; 32]> {
    if to_epoch < from_epoch {
        return None;
    }
    if to_epoch - from_epoch > 8192 {
        return None;
    }
    let mut k = *key;
    for e in (from_epoch + 1)..=to_epoch {
        let mut material = [0u8; 36];
        material[..32].copy_from_slice(&k);
        material[32..].copy_from_slice(&e.to_be_bytes());
        let next = blake3::derive_key("mesh-core:v1:pairratchet", &material);
        // M5: every intermediate here is a PAST epoch's key, and the whole point of the
        // ratchet is that those become unrecoverable. Leaving them on the stack — which a
        // long catch-up now fills thousands of copies of — undercuts exactly that claim.
        material.zeroize();
        k.zeroize();
        k = next;
    }
    Some(k)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_beacon_seed(val: u8) -> [u8; 32] {
        [val; 32]
    }

    #[test]
    fn from_seed_deterministic() {
        let seed: [u8; 32] =
            hex::decode("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")
                .unwrap()
                .try_into()
                .unwrap();
        let bs = test_beacon_seed(7);

        // Same seed + beacon_seed → deterministic key.
        let e1 = from_seed(&seed, &bs);
        let e2 = from_seed(&seed, &bs);
        assert_eq!(public_key(&e1), public_key(&e2));

        // Different beacon_seed → different key (forward-secrecy rotation).
        let bs2 = test_beacon_seed(8);
        let e3 = from_seed(&seed, &bs2);
        assert_ne!(public_key(&e1), public_key(&e3));

        // Sign + verify roundtrip with derived key.
        let canon = b"test message for derived key";
        let sig = sign(&e1, canon);
        let pk = public_key(&e1);
        assert!(verify(&pk, canon, &sig));
    }

    #[test]
    fn ed25519_rejects_tamper() {
        let seed: [u8; 32] =
            hex::decode("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")
                .unwrap()
                .try_into()
                .unwrap();
        let bs = test_beacon_seed(7);

        let canon = hex::decode(
            "01080f161d242b323940474e555c636a71787f868d949ba2a9b0b7bec5ccd3dae1e8eff6fd040b121920272e353c434a51585f666d747b828990979ea5acb3bac1c8cfd6dde4ebf2f900070e151c232a31383f464d545b626970777e858c939aa1a8afb6bdc4cbd2d9e0e7eef5fc030a11181f262d34",
        )
        .unwrap();

        let e = from_seed(&seed, &bs);
        let pk = public_key(&e);
        let sig = sign(&e, &canon);

        // flip sig[0]
        let mut bad_sig = sig;
        bad_sig[0] ^= 0xff;
        assert!(!verify(&pk, &canon, &bad_sig));

        // flip canon byte
        let mut bad_canon = canon.clone();
        bad_canon[0] ^= 0xff;
        assert!(!verify(&pk, &bad_canon, &sig));

        // flip pubkey[0]
        let mut bad_pk = pk;
        bad_pk[0] ^= 0xff;
        assert!(!verify(&bad_pk, &canon, &sig));
    }

    #[test]
    fn rotate_is_random() {
        let e1 = rotate();
        let e2 = rotate();
        assert_ne!(public_key(&e1), public_key(&e2));
    }

    #[test]
    fn aead_kat() {
        let key: [u8; 32] =
            hex::decode("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")
                .unwrap()
                .try_into()
                .unwrap();

        let nonce: [u8; 12] = hex::decode("000102030405060708090a0b")
            .unwrap()
            .try_into()
            .unwrap();

        let pt =
            hex::decode("726567696f6e616c2d70726f706167617465642064616e67657220616c657274207630")
                .unwrap();

        let expected_ct = hex::decode(
            "fb9e6f694679c42c9af34d9ce87c6902bd15d6c73515c3de83e50fa419a5d448ccf61cef3e01959294d46410cd721f19611f5e",
        )
        .unwrap();

        let ct = aead_seal(&key, &nonce, &pt);
        assert_eq!(ct, expected_ct);

        let decrypted = aead_open(&key, &nonce, &ct);
        assert_eq!(decrypted, Some(pt));
    }

    fn hex_to_32(s: &str) -> [u8; 32] {
        let mut out = [0u8; 32];
        for i in 0..32 {
            out[i] = u8::from_str_radix(&s[i * 2..i * 2 + 2], 16).unwrap();
        }
        out
    }

    #[test]
    fn pair_public_kat() {
        let a_sk: [u8; 32] = core::array::from_fn(|i| i as u8);
        let b_sk: [u8; 32] = core::array::from_fn(|i| (i + 32) as u8);
        let a_pk_expect = hex_to_32("8f40c5adb68f25624ae5b214ea767a6ec94d829d3d7b5e1ad1ba6f3e2138285f");
        let b_pk_expect = hex_to_32("358072d6365880d1aeea329adf9121383851ed21a28e3b75e965d0d2cd166254");
        assert_eq!(pair_public(&a_sk), a_pk_expect);
        assert_eq!(pair_public(&b_sk), b_pk_expect);
    }

    #[test]
    fn pair_derive_symmetric_and_domain_separated() {
        let a_sk: [u8; 32] = core::array::from_fn(|i| i as u8);
        let b_sk: [u8; 32] = core::array::from_fn(|i| (i + 32) as u8);
        let a_pk = pair_public(&a_sk);
        let b_pk = pair_public(&b_sk);
        let k1 = pair_derive(&a_sk, &b_pk).unwrap();
        let k2 = pair_derive(&b_sk, &a_pk).unwrap();
        assert_eq!(k1, k2);
        // Key must be the domain-separated derivation of the raw DH output, not the raw DH itself.
        let raw_dh = hex_to_32("9663aa1da97e848a914a436d04163dfbb89178f107f1b5b77ed3854203382854");
        assert_eq!(k1, blake3::derive_key("mesh-core:v1:pairkey", &raw_dh));
        assert_ne!(k1, raw_dh);
    }

    #[test]
    fn pair_derive_rejects_low_order_zero_output() {
        let a_sk: [u8; 32] = core::array::from_fn(|i| i as u8);
        // The identity point as peer public key forces an all-zero DH output.
        assert_eq!(pair_derive(&a_sk, &[0u8; 32]), None);
    }

    #[test]
    fn pair_seed_v2_salt_order_invariant() {
        let shared: [u8; 32] = core::array::from_fn(|i| (i + 7) as u8);
        let salt_a: [u8; 32] = core::array::from_fn(|i| (i * 3) as u8);
        let salt_b: [u8; 32] = core::array::from_fn(|i| (i * 5 + 1) as u8);
        // Both parties must derive the same seed regardless of argument order.
        assert_eq!(
            pair_seed_v2(&shared, &salt_a, &salt_b),
            pair_seed_v2(&shared, &salt_b, &salt_a)
        );
        // A different salt set → a different seed.
        let salt_c: [u8; 32] = core::array::from_fn(|i| (i * 7 + 2) as u8);
        assert_ne!(
            pair_seed_v2(&shared, &salt_a, &salt_b),
            pair_seed_v2(&shared, &salt_a, &salt_c)
        );
    }

    #[test]
    fn pair_sas_is_order_independent_and_binds_both_identities() {
        let shared: [u8; 32] = [0x11; 32];
        let pk_a: [u8; 32] = core::array::from_fn(|i| i as u8);
        let pk_b: [u8; 32] = core::array::from_fn(|i| (255 - i) as u8);

        // Both sides must derive the same string without knowing whose key is whose.
        assert_eq!(pair_sas(&shared, &pk_a, &pk_b), pair_sas(&shared, &pk_b, &pk_a));

        // A man-in-the-middle holds a DIFFERENT shared secret with each side. That is the
        // whole mechanism: if this ever compared equal, the SAS would authenticate nothing.
        let shared_mitm: [u8; 32] = [0x22; 32];
        assert_ne!(pair_sas(&shared, &pk_a, &pk_b), pair_sas(&shared_mitm, &pk_a, &pk_b));

        // Substituting an identity must also change it, so a relay cannot reuse one leg's
        // string while presenting its own key to the other side.
        let pk_m: [u8; 32] = [0x77; 32];
        assert_ne!(pair_sas(&shared, &pk_a, &pk_b), pair_sas(&shared, &pk_a, &pk_m));
    }

    #[test]
    fn sas_words_cover_the_table_exactly() {
        // 16 onsets x 8 vowels x 16 codas = 2048 = 2^11, so every 11-bit index maps to a
        // distinct word and none is unreachable. A table that was not a power of two would
        // silently bias the string and cost entropy.
        assert_eq!(SAS_ONSETS.len() * SAS_VOWELS.len() * SAS_CODAS.len(), 2048);

        let words = sas_words(&[0u8; 8]);
        assert_eq!(words.len(), SAS_WORD_COUNT);
        assert_eq!(words, vec!["bab", "bab", "bab", "bab"]);

        // All-ones in the top 44 bits selects the last entry of every column.
        let words = sas_words(&[0xFF; 8]);
        assert_eq!(words, vec!["zaish", "zaish", "zaish", "zaish"]);

        // Deterministic, and a change inside the consumed bits changes the string.
        let a = sas_words(&[1, 2, 3, 4, 5, 6, 7, 8]);
        assert_eq!(a, sas_words(&[1, 2, 3, 4, 5, 6, 7, 8]));
        assert_ne!(a, sas_words(&[2, 2, 3, 4, 5, 6, 7, 8]));

        // Only the top 44 bits are consumed, so the low 20 are deliberately ignored. Pinned
        // because it bounds the strength: this string is 44 bits, not 64, and any future
        // change to SAS_WORD_COUNT must be reasoned about against that.
        // Byte 5 straddles the boundary: its high nibble is consumed, its low nibble is not.
        assert_eq!(a, sas_words(&[1, 2, 3, 4, 5, 0x0F, 0xFF, 0xFF]));
    }

    #[test]
    fn pair_ratchet_is_one_way_and_deterministic() {
        let k0: [u8; 32] = [0x42; 32];
        // Same span → same key.
        assert_eq!(pair_ratchet(&k0, 10, 13), pair_ratchet(&k0, 10, 13));
        // Different span → different key.
        assert_ne!(pair_ratchet(&k0, 10, 13), pair_ratchet(&k0, 10, 14));
        // Chaining matches stepping: ratchet(10→11) then (11→13) == ratchet(10→13).
        let k11 = pair_ratchet(&k0, 10, 11).unwrap();
        assert_eq!(pair_ratchet(&k11, 11, 13), pair_ratchet(&k0, 10, 13));
        // Identity span returns the input.
        assert_eq!(pair_ratchet(&k0, 7, 7), Some(k0));
        // Backwards and absurd spans are refused.
        assert_eq!(pair_ratchet(&k0, 13, 10), None);
        assert_eq!(pair_ratchet(&k0, 0, 9000), None);
    }

    #[test]
    fn aead_rejects_tamper() {
        let key: [u8; 32] =
            hex::decode("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")
                .unwrap()
                .try_into()
                .unwrap();

        let nonce: [u8; 12] = hex::decode("000102030405060708090a0b")
            .unwrap()
            .try_into()
            .unwrap();

        let mut ct = hex::decode(
            "fb9e6f694679c42c9af34d9ce87c6902bd15d6c73515c3de83e50fa419a5d448ccf61cef3e01959294d46410cd721f19611f5e",
        )
        .unwrap();

        ct[0] ^= 0xff;
        assert_eq!(aead_open(&key, &nonce, &ct), None);
    }
}
