//! `crypto` — ephemeral Ed25519 identity (beacon-rotating) + AEAD.
//!
//! Constant-time verify. Domain-separated signatures. Keys derived from static device seed +
//! beacon seed for forward secrecy. Persisted only via the platform `KeyStore` trait
//! (Keystore/Keychain) — never written to core-owned storage (invariant #5).
//! See README.md §2.

use chacha20poly1305::{ChaCha20Poly1305, KeyInit, Nonce, aead::Aead};
use ed25519_dalek::{Signature, Signer, SigningKey, VerifyingKey};

pub const DOMAIN_SIG: &[u8] = b"mesh-core:v1:frame-sig";

/// A rotating ephemeral signing identity. Derived from the static device seed and the
/// per-epoch beacon seed (forward-secrecy chain). Rotates with the beacon, never persisted
/// beyond the platform secure store, wiped on panic-wipe.
pub struct Ephemeral {
    key: SigningKey,
}

/// Secure key storage owned by the platform shim (Android Keystore / iOS Keychain).
pub trait KeyStore {
    fn load_seed(&self) -> Option<[u8; 32]>;
    fn store_seed(&self, seed: &[u8; 32]);
    fn wipe(&self);
}

/// Derive an ephemeral signing key from the static device `seed` and the current `beacon_seed`.
///
/// The beacon seed provides forward secrecy: even if the static seed is extracted later,
/// past ephemeral keys cannot be recomputed without the past beacon seed — and the one-way
/// hash chain makes those unrecoverable.
pub fn from_seed(seed: &[u8; 32], beacon_seed: &[u8; 32]) -> Ephemeral {
    let mut material = [0u8; 64];
    material[..32].copy_from_slice(seed);
    material[32..].copy_from_slice(beacon_seed);
    let derived = blake3::derive_key("mesh-core:v1:ephemeral", &material);
    Ephemeral {
        key: SigningKey::from_bytes(&derived),
    }
}

/// Create a fresh ephemeral identity (random seed + random beacon seed).
/// Used for panic-wipe + restart — unlinkable to any prior identity.
pub fn rotate() -> Ephemeral {
    let mut seed = [0u8; 32];
    getrandom::fill(&mut seed).expect("OS CSPRNG unavailable");
    let mut beacon_seed = [0u8; 32];
    getrandom::fill(&mut beacon_seed).expect("OS CSPRNG unavailable");
    from_seed(&seed, &beacon_seed)
}

pub fn public_key(e: &Ephemeral) -> [u8; 32] {
    e.key.verifying_key().to_bytes()
}

pub fn sign(e: &Ephemeral, canonical: &[u8]) -> [u8; 64] {
    let msg = [DOMAIN_SIG, canonical].concat();
    e.key.sign(&msg).to_bytes()
}

pub fn verify(pk: &[u8; 32], canonical: &[u8], sig: &[u8; 64]) -> bool {
    let vk = match VerifyingKey::from_bytes(pk) {
        Ok(v) => v,
        Err(_) => return false,
    };
    let s = Signature::from_bytes(sig);
    let msg = [DOMAIN_SIG, canonical].concat();
    vk.verify_strict(&msg, &s).is_ok()
}

pub fn aead_seal(key: &[u8; 32], nonce: &[u8; 12], pt: &[u8]) -> Vec<u8> {
    ChaCha20Poly1305::new_from_slice(key)
        .expect("32-byte key")
        .encrypt(&Nonce::from(*nonce), pt)
        .expect("aead encrypt")
}

pub fn aead_open(key: &[u8; 32], nonce: &[u8; 12], ct: &[u8]) -> Option<Vec<u8>> {
    ChaCha20Poly1305::new_from_slice(key)
        .ok()?
        .decrypt(&Nonce::from(*nonce), ct)
        .ok()
}

/// X25519 public key for a long-term pairing secret. The secret is generated by the caller
/// (32 random bytes from the OS RNG) and never leaves the device.
pub fn pair_public(sk: &[u8; 32]) -> [u8; 32] {
    let secret = x25519_dalek::StaticSecret::from(*sk);
    x25519_dalek::PublicKey::from(&secret).to_bytes()
}

/// Derive the shared pairwise message key from our secret and the peer's public key.
/// Returns None if the DH output is the all-zero point (contributory behaviour check).
/// Both sides derive the identical key. Domain-separated via blake3 derive_key.
pub fn pair_derive(our_sk: &[u8; 32], their_pk: &[u8; 32]) -> Option<[u8; 32]> {
    let secret = x25519_dalek::StaticSecret::from(*our_sk);
    let shared = secret.diffie_hellman(&x25519_dalek::PublicKey::from(*their_pk));
    if shared.as_bytes().iter().all(|&b| b == 0) {
        return None;
    }
    Some(blake3::derive_key("mesh-core:v1:pairkey", shared.as_bytes()))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_beacon_seed(val: u8) -> [u8; 32] {
        [val; 32]
    }

    #[test]
    fn from_seed_deterministic() {
        let seed: [u8; 32] =
            hex::decode("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")
                .unwrap()
                .try_into()
                .unwrap();
        let bs = test_beacon_seed(7);

        // Same seed + beacon_seed → deterministic key.
        let e1 = from_seed(&seed, &bs);
        let e2 = from_seed(&seed, &bs);
        assert_eq!(public_key(&e1), public_key(&e2));

        // Different beacon_seed → different key (forward-secrecy rotation).
        let bs2 = test_beacon_seed(8);
        let e3 = from_seed(&seed, &bs2);
        assert_ne!(public_key(&e1), public_key(&e3));

        // Sign + verify roundtrip with derived key.
        let canon = b"test message for derived key";
        let sig = sign(&e1, canon);
        let pk = public_key(&e1);
        assert!(verify(&pk, canon, &sig));
    }

    #[test]
    fn ed25519_rejects_tamper() {
        let seed: [u8; 32] =
            hex::decode("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")
                .unwrap()
                .try_into()
                .unwrap();
        let bs = test_beacon_seed(7);

        let canon = hex::decode(
            "01080f161d242b323940474e555c636a71787f868d949ba2a9b0b7bec5ccd3dae1e8eff6fd040b121920272e353c434a51585f666d747b828990979ea5acb3bac1c8cfd6dde4ebf2f900070e151c232a31383f464d545b626970777e858c939aa1a8afb6bdc4cbd2d9e0e7eef5fc030a11181f262d34",
        )
        .unwrap();

        let e = from_seed(&seed, &bs);
        let pk = public_key(&e);
        let sig = sign(&e, &canon);

        // flip sig[0]
        let mut bad_sig = sig;
        bad_sig[0] ^= 0xff;
        assert!(!verify(&pk, &canon, &bad_sig));

        // flip canon byte
        let mut bad_canon = canon.clone();
        bad_canon[0] ^= 0xff;
        assert!(!verify(&pk, &bad_canon, &sig));

        // flip pubkey[0]
        let mut bad_pk = pk;
        bad_pk[0] ^= 0xff;
        assert!(!verify(&bad_pk, &canon, &sig));
    }

    #[test]
    fn rotate_is_random() {
        let e1 = rotate();
        let e2 = rotate();
        assert_ne!(public_key(&e1), public_key(&e2));
    }

    #[test]
    fn aead_kat() {
        let key: [u8; 32] =
            hex::decode("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")
                .unwrap()
                .try_into()
                .unwrap();

        let nonce: [u8; 12] = hex::decode("000102030405060708090a0b")
            .unwrap()
            .try_into()
            .unwrap();

        let pt =
            hex::decode("726567696f6e616c2d70726f706167617465642064616e67657220616c657274207630")
                .unwrap();

        let expected_ct = hex::decode(
            "fb9e6f694679c42c9af34d9ce87c6902bd15d6c73515c3de83e50fa419a5d448ccf61cef3e01959294d46410cd721f19611f5e",
        )
        .unwrap();

        let ct = aead_seal(&key, &nonce, &pt);
        assert_eq!(ct, expected_ct);

        let decrypted = aead_open(&key, &nonce, &ct);
        assert_eq!(decrypted, Some(pt));
    }

    fn hex_to_32(s: &str) -> [u8; 32] {
        let mut out = [0u8; 32];
        for i in 0..32 {
            out[i] = u8::from_str_radix(&s[i * 2..i * 2 + 2], 16).unwrap();
        }
        out
    }

    #[test]
    fn pair_public_kat() {
        let a_sk: [u8; 32] = core::array::from_fn(|i| i as u8);
        let b_sk: [u8; 32] = core::array::from_fn(|i| (i + 32) as u8);
        let a_pk_expect = hex_to_32("8f40c5adb68f25624ae5b214ea767a6ec94d829d3d7b5e1ad1ba6f3e2138285f");
        let b_pk_expect = hex_to_32("358072d6365880d1aeea329adf9121383851ed21a28e3b75e965d0d2cd166254");
        assert_eq!(pair_public(&a_sk), a_pk_expect);
        assert_eq!(pair_public(&b_sk), b_pk_expect);
    }

    #[test]
    fn pair_derive_symmetric_and_domain_separated() {
        let a_sk: [u8; 32] = core::array::from_fn(|i| i as u8);
        let b_sk: [u8; 32] = core::array::from_fn(|i| (i + 32) as u8);
        let a_pk = pair_public(&a_sk);
        let b_pk = pair_public(&b_sk);
        let k1 = pair_derive(&a_sk, &b_pk).unwrap();
        let k2 = pair_derive(&b_sk, &a_pk).unwrap();
        assert_eq!(k1, k2);
        // Key must be the domain-separated derivation of the raw DH output, not the raw DH itself.
        let raw_dh = hex_to_32("9663aa1da97e848a914a436d04163dfbb89178f107f1b5b77ed3854203382854");
        assert_eq!(k1, blake3::derive_key("mesh-core:v1:pairkey", &raw_dh));
        assert_ne!(k1, raw_dh);
    }

    #[test]
    fn pair_derive_rejects_low_order_zero_output() {
        let a_sk: [u8; 32] = core::array::from_fn(|i| i as u8);
        // The identity point as peer public key forces an all-zero DH output.
        assert_eq!(pair_derive(&a_sk, &[0u8; 32]), None);
    }

    #[test]
    fn aead_rejects_tamper() {
        let key: [u8; 32] =
            hex::decode("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")
                .unwrap()
                .try_into()
                .unwrap();

        let nonce: [u8; 12] = hex::decode("000102030405060708090a0b")
            .unwrap()
            .try_into()
            .unwrap();

        let mut ct = hex::decode(
            "fb9e6f694679c42c9af34d9ce87c6902bd15d6c73515c3de83e50fa419a5d448ccf61cef3e01959294d46410cd721f19611f5e",
        )
        .unwrap();

        ct[0] ^= 0xff;
        assert_eq!(aead_open(&key, &nonce, &ct), None);
    }
}
